AWSTemplateFormatVersion: '2010-09-09'
Description: 'Risky IAM Policy for Checkov Testing'

Resources:
  RiskyIAMPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: 'CheckovTestRiskyPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action: '*'
            Resource: '*'

