AWSTemplateFormatVersion: "2010-09-09"
Description: Stack 2 - IAM Roles and Policies (Roles 4-5)

Resources:
  ODBDeveloperRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: odb-viewonly-role
      #RoleName: odb-admin-role
      #RoleName: odb-admin-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: odb.amazonaws.com
            Action: sts:AssumeRole

  ODBReaderPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: stack2-odb-reader-policy
      Roles:
        - !Ref ODBDeveloperRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - odb:*create*
            Resource: "*"